# Generated by Django 2.2.6 on 2019-10-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('tipo_despesa', models.CharField(choices=[('Remedio', 'Remedio'), ('Roupa', 'Roupa'), ('Alimentação', 'Alimentação'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], default='6', max_length=10, verbose_name='Tipo Despesa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('forma_pagamento', models.CharField(choices=[('CAD', 'cartao de debito'), ('CAC', 'cartao de credito'), ('CRE', 'cartao Crediario'), ('CHE', 'cheque'), ('DI', 'dinheiro')], default='DI', max_length=3, verbose_name='forma pagamento')),
                ('vencimento', models.DateField(verbose_name='Data vencimento')),
                ('quitacao', models.BooleanField(verbose_name='Quitação')),
            ],
            options={
                'verbose_name': 'Controle de gasto',
                'verbose_name_plural': 'Controles de gastos',
            },
        ),
    ]
